export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_FAILURE="LOGIN_FAILURE";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const GET_USER='GET_USER';
export const REGISTER_USER='REGISTER_USER';